### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by yancccc** [alaradirik/google-cloud-flask-tutorial#3]
Hi，
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

I followed your instructions completely（Python3.7， pip install -r requirements.txt，request.py url = "http://192.168.1.196:5000/predict"）, but I still couldn't， why?

**Comment by yancccc** [comment]
I really need your help.

**Comment by alaradirik** [comment]
Hi @yancccc, have you edited the firewall rules to accept incoming requests at port 5000? And are you using the external IP of your server?
